export let images = [
    '<i class="fa fa-vk" aria-hidden="true"></i>',
    '<i class="fa fa-vk" aria-hidden="true"></i>',
    '<i class="fa fa-tumblr" aria-hidden="true"></i>',
    '<i class="fa fa-tumblr" aria-hidden="true"></i>', 
    '<i class="fa fa-telegram" aria-hidden="true"></i>',
    '<i class="fa fa-telegram" aria-hidden="true"></i>',
    '<i class="fa fa-html5" aria-hidden="true"></i>',
    '<i class="fa fa-html5" aria-hidden="true"></i>',
    '<i class="fa fa-github-square" aria-hidden="true"></i>',
    '<i class="fa fa-github-square" aria-hidden="true"></i>',
    '<i class="fa fa-css3" aria-hidden="true"></i>',
    '<i class="fa fa-css3" aria-hidden="true"></i>',
    '<i class="fa fa-soundcloud" aria-hidden="true"></i>',
    '<i class="fa fa-soundcloud" aria-hidden="true"></i>',
    '<i class="fa fa-chrome" aria-hidden="true"></i>',
    '<i class="fa fa-chrome" aria-hidden="true"></i>',
    '<i class="fa fa-youtube-play" aria-hidden="true"></i>',
    '<i class="fa fa-youtube-play" aria-hidden="true"></i>',
    '<i class="fa fa-stack-overflow" aria-hidden="true"></i>',
    '<i class="fa fa-stack-overflow" aria-hidden="true"></i>',
    '<i class="fa fa-firefox" aria-hidden="true"></i>',
    '<i class="fa fa-firefox" aria-hidden="true"></i>',
    '<i class="fa fa-jsfiddle" aria-hidden="true"></i>',
    '<i class="fa fa-jsfiddle" aria-hidden="true"></i>'
];
